### ISSUE TITLE
AttributeError: 'AttributeError' object has no attribute 'message'

### ISSUE THREAD

**Issue by emgent** [gcrahay/otx_misp#11]
Hello *,
Any hint? :-)

$ otx-misp -o <AV_API_KEY> -s https://misp.domain.tld -m <AV_API_KEY> --to-ids --distribution community --discover-tags
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/otx_misp/cli.py", line 151, in main
    create_events(pulses, author=config.author, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/otx_misp/__init__.py", line 138, in create_events
    for pulse in pulse_or_list]
  File "/usr/local/lib/python3.4/dist-packages/otx_misp/__init__.py", line 138, in <listcomp>
    for pulse in pulse_or_list]
  File "/usr/local/lib/python3.4/dist-packages/otx_misp/__init__.py", line 180, in create_events
    misp.add_tag(event, tag)
  File "/usr/local/lib/python3.4/dist-packages/pymisp/api.py", line 55, in new_func
    filename=func.func_code.co_filename,
AttributeError: 'function' object has no attribute 'func_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/otx-misp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/otx_misp/cli.py", line 153, in main
    log.error(ex.message)
AttributeError: 'AttributeError' object has no attribute 'message'
$

**Comment by gudsaf** [comment]
has same problem

do you upgrade anything under this problem appeared?

**Comment by gcrahay** [comment]
There were an issue in PyMISP (fixed MISP/PyMISP#94 ) and an issue in otx-misp (fixed in version 1.2.1).

This should now work with the latest versions.
