### ISSUE TITLE
AttributeError: 'IndexError' object has no attribute 'message'

### ISSUE THREAD

**Issue by KALRONG** [gcrahay/otx_misp#18]
### Description

While dry run works when I disable it I keep getting this error after the script queries MISP (I can see it in the server usage).

### Versions

- otx-misp: 1.4.0 (installed via pip)
- PyMISP: 2.4.77
- MISP:2.4.78
- Python (Python 2 will not be supported): 3
- Operating system: Debian 9

### Traceback or error

Connection to MISP instance: https://172.24.2.1:2443
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/otx_misp/cli.py", line 165, in main
    create_events(pulses, author=config.author, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/otx_misp/__init__.py", line 185, in create_events
    tags[get_tag_name(tag['name'])] = tag['name']
  File "/usr/local/lib/python3.5/dist-packages/otx_misp/__init__.py", line 177, in get_tag_name
    if last[0] == '"':
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/otx-misp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/otx_misp/cli.py", line 167, in main
    log.error(ex.message)
AttributeError: 'IndexError' object has no attribute 'message'

**Comment by KALRONG** [comment]
I found that the issue were some tags existing in my misp that didn't contain a value after the "=" I have applied a little fix and now its working, here is my pull request: https://github.com/gcrahay/otx_misp/pull/19
