### ISSUE TITLE
Unable to download pulses from otx_misp python sdk module

### ISSUE THREAD

**Issue by shreyaganvir** [gcrahay/otx_misp#43]
### Description
I am trying to download pulses from Alienvault OTX using OTX key from a specific timestamp. I have executed this code several times in last 6 months and it was working fine till last executed on 6th september 2021. Today I m facing below error mentioned in ##Traceback section. I supposed the issue might be due to temp connection issue. but the error is persistent since few hrs now. This is a snippet of production code . Kindly let me know if anyone has a solution

Source code is as follows
import otx_misp
import urllib3
import sys
import os
import pytz
import datetime
import pymisp

urllib3.disable_warnings()
__version__ = "1.4.2"

class ImportException(Exception):
    pass

otx_pulses = otx_misp.get_pulses(<OTX_key>, 2021-09-12 16:17:50.457452+00:00)

### Versions

- otx-misp: 1.4.3
- PyMISP: 2.4.144
- MISP:
- Python (Python 2 will not be supported): 3.8.10
- Operating system: Ubuntu 20.04

### Traceback or error
Traceback (most recent call last):
  File "otx_ingestion_to_misp.py", line 141, in <module>
    otx_pulses = otx_misp.get_pulses(args["otx_key"], args["fromdate"])
  File "/home/test/.local/lib/python3.8/site-packages/otx_misp/__init__.py", line 110, in get_pulses
    pulses = otx.getsince(from_timestamp)
  File "/home/test/.local/lib/python3.8/site-packages/otx_misp/otx/OTXv2.py", line 129, in getsince
    json_data = self.get(next)
  File "/home/test/.local/lib/python3.8/site-packages/otx_misp/otx/OTXv2.py", line 77, in get
    data = response.read().decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'read'

**Comment by MarkXiangY** [comment]
Running into a similar "AttributeError: 'NoneType' object has no attribute 'read' " error with just running the __main__ script. Started a week ago or so.

**Comment by shreyaganvir** [comment]
> Running into a similar "AttributeError: 'NoneType' object has no attribute 'read' " error with just running the **main** script. Started a week ago or so.

@MarkXiangY above error was due to endpoint API change of API_V1_ROOT = "/api/v1/" changed to API_V1_ROOT = "/api/v1" from OTXv2.py module (extra fwd slash appeared in API_V1_ROOT due to which download uri was created incorrectly)  

Check out this link https://github.com/AlienVault-OTX/OTX-Python-SDK, seems to be similar project like otx-misp.
